/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

extern "C" {

// Modelname: expl_parfn_cond1
// Variables: none
// Parameters: k_act_R_bas, k_deact_R, totA, k1, k2, pA, k_act_R, Km, Km2
// Outputs: Stim, R, A, pA, k_act_R_bas, k_act_R, k_deact_R, k1, Km, k2, Km2

void expl_parfn_cond1_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    for (int obs = 0; obs < n_obs; obs++) {
        // Stim
        y[obs * n_out + 0] = 1.0;

        // R
        y[obs * n_out + 1] = std::pow(10.0, p[0])*std::pow(10.0, -p[1]);

        // A
        y[obs * n_out + 2] = std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0);

        // pA
        y[obs * n_out + 3] = std::pow(10.0, p[5]);

        // k_act_R_bas
        y[obs * n_out + 4] = std::pow(10.0, p[0]);

        // k_act_R
        y[obs * n_out + 5] = std::pow(10.0, p[6]);

        // k_deact_R
        y[obs * n_out + 6] = std::pow(10.0, p[1]);

        // k1
        y[obs * n_out + 7] = std::pow(10.0, p[4])*std::pow(10.0, -p[0])*std::pow(10.0, p[1])*std::pow(10.0, p[5])*std::pow(10.0, -p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));

        // Km
        y[obs * n_out + 8] = std::pow(10.0, p[7]);

        // k2
        y[obs * n_out + 9] = std::pow(10.0, p[4]);

        // Km2
        y[obs * n_out + 10] = std::pow(10.0, p[8]);

    }
}

void expl_parfn_cond1_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 11;
    const int n_symbols = 9;

    // Zero-initialize
    std::fill(jac, jac + n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        jac[obs + n_obs * (1 + n_out * 0)] = std::pow(10.0, p[0] - p[1])*std::log(10.0);
        jac[obs + n_obs * (1 + n_out * 1)] = -std::pow(10.0, p[0] - p[1])*std::log(10.0);

        jac[obs + n_obs * (2 + n_out * 0)] = -std::pow(10.0, p[3] - p[4] + p[0] - p[1] + p[2])*std::log(10.0)/std::pow(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0, 2.0);
        jac[obs + n_obs * (2 + n_out * 1)] = std::pow(10.0, p[3] - p[4] + p[0] - p[1] + p[2])*std::log(10.0)/std::pow(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0, 2.0);
        jac[obs + n_obs * (2 + n_out * 2)] = std::pow(10.0, p[2])*std::log(10.0)/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0);
        jac[obs + n_obs * (2 + n_out * 3)] = -std::pow(10.0, p[3] - p[4] + p[0] - p[1] + p[2])*std::log(10.0)/std::pow(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0, 2.0);
        jac[obs + n_obs * (2 + n_out * 4)] = std::pow(10.0, p[3] - p[4] + p[0] - p[1] + p[2])*std::log(10.0)/std::pow(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0, 2.0);

        jac[obs + n_obs * (3 + n_out * 5)] = std::pow(10.0, p[5])*std::log(10.0);

        jac[obs + n_obs * (4 + n_out * 0)] = std::pow(10.0, p[0])*std::log(10.0);

        jac[obs + n_obs * (5 + n_out * 6)] = std::pow(10.0, p[6])*std::log(10.0);

        jac[obs + n_obs * (6 + n_out * 1)] = std::pow(10.0, p[1])*std::log(10.0);

        jac[obs + n_obs * (7 + n_out * 0)] = -std::pow(10.0, p[3] + p[5])*std::log(10.0)/((std::pow(10.0, p[8]) + std::pow(10.0, p[5]))*(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0)) + std::pow(10.0, p[3] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5])) - std::pow(10.0, p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 1)] = std::pow(10.0, p[3] + p[5])*std::log(10.0)/((std::pow(10.0, p[8]) + std::pow(10.0, p[5]))*(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0)) - std::pow(10.0, p[3] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5])) + std::pow(10.0, p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 2)] = std::pow(10.0, p[4] - p[0] + p[1] + p[5])*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5])) - std::pow(10.0, p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 3)] = -std::pow(10.0, p[3] + p[5])*std::log(10.0)/((std::pow(10.0, p[8]) + std::pow(10.0, p[5]))*(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0)) + std::pow(10.0, p[3] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 4)] = std::pow(10.0, p[3] + p[5])*std::log(10.0)/((std::pow(10.0, p[8]) + std::pow(10.0, p[5]))*(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0)) - std::pow(10.0, p[3] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5])) + std::pow(10.0, p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 5)] = std::pow(10.0, p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5])) - std::pow(10.0, p[4] - p[0] + p[1] + 2.0*p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/std::pow(std::pow(10.0, p[8]) + std::pow(10.0, p[5]), 2.0);
        jac[obs + n_obs * (7 + n_out * 7)] = std::pow(10.0, p[7] + p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/(std::pow(10.0, p[8]) + std::pow(10.0, p[5]));
        jac[obs + n_obs * (7 + n_out * 8)] = -std::pow(10.0, p[8] + p[4] - p[0] + p[1] + p[5] - p[2])*(std::pow(10.0, p[7]) + std::pow(10.0, p[2])/(std::pow(10.0, p[3])*std::pow(10.0, -p[4])*std::pow(10.0, p[0])*std::pow(10.0, -p[1]) + 1.0))*(std::pow(10.0, p[3] - p[4] + p[0] - p[1]) + 1.0)*std::log(10.0)/std::pow(std::pow(10.0, p[8]) + std::pow(10.0, p[5]), 2.0);

        jac[obs + n_obs * (8 + n_out * 7)] = std::pow(10.0, p[7])*std::log(10.0);

        jac[obs + n_obs * (9 + n_out * 4)] = std::pow(10.0, p[4])*std::log(10.0);

        jac[obs + n_obs * (10 + n_out * 8)] = std::pow(10.0, p[8])*std::log(10.0);

    }
}

} // extern "C"
