/** Code auto-generated by CppODE 1.0.0 **/

#include <cmath>
#include <algorithm>

extern "C" {

// Modelname: expl_parfn
// Variables: none
// Parameters: k
// Outputs: x, k

void expl_parfn_eval(double* x, double* y, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    const int n_out  = *l;
    (void)n_vars;  // suppress unused warning

    for (int obs = 0; obs < n_obs; obs++) {
        // x
        y[obs * n_out + 0] = 1.0;

        // k
        y[obs * n_out + 1] = p[0];

    }
}

void expl_parfn_jacobian(double* x, double* jac, double* p, int* n, int* k, int* l) {
    const int n_obs = *n;
    const int n_vars = *k;
    (void)n_vars;  // suppress unused warning
    const int n_out = 2;
    const int n_symbols = 1;

    // Zero-initialize
    std::fill(jac, jac + n_obs * n_out * n_symbols, 0.0);

    // Layout: jac[obs, output, symbol] (R column-major)
    // Linear index: obs + n_obs * (output + n_out * symbol)
    for (int obs = 0; obs < n_obs; obs++) {
        jac[obs + n_obs * (1 + n_out * 0)] = 1.0;

    }
}

} // extern "C"
