// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// resCpp
Rcpp::List resCpp(Rcpp::DataFrame data, SEXP out, Rcpp::Nullable<Rcpp::DataFrame> err, std::string optBLOQ);
RcppExport SEXP _dMod_resCpp(SEXP dataSEXP, SEXP outSEXP, SEXP errSEXP, SEXP optBLOQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out(outSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type err(errSEXP);
    Rcpp::traits::input_parameter< std::string >::type optBLOQ(optBLOQSEXP);
    rcpp_result_gen = Rcpp::wrap(resCpp(data, out, err, optBLOQ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dMod_resCpp", (DL_FUNC) &_dMod_resCpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dMod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
