// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// res_cpp
List res_cpp(DataFrame data, NumericMatrix out, Nullable<NumericMatrix> err);
RcppExport SEXP _dMod_res_cpp(SEXP dataSEXP, SEXP outSEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type out(outSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(res_cpp(data, out, err));
    return rcpp_result_gen;
END_RCPP
}
