# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute residuals (Rcpp implementation)
#' 
#' @param data DataFrame with columns: time, name, value, sigma, lloq
#' @param out NumericMatrix with predictions (first column = time)
#' @param err Nullable NumericMatrix with error model predictions
#' @return List with data and derivatives as 2D/3D arrays
#' @export
res_cpp <- function(data, out, err = NULL) {
    .Call(`_dMod_res_cpp`, data, out, err)
}

