# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute residuals (Rcpp implementation, optimized)
#'
#' @param data DataFrame with columns: time, name, value, sigma, lloq
#' @param out NumericMatrix with predictions (first column = time)
#' @param err Nullable NumericMatrix with error model predictions
#' @return List with:
#'   - data: DataFrame with residual columns
#'   - deriv:  NumericMatrix n_data × n_pars (first derivatives of out)
#'   - deriv2: NumericArray  n_data × n_pars × n_pars (second derivatives of out)
#'   - deriv.err:  NumericMatrix n_data × n_pars (first derivatives of err sigma-part)
#'   - deriv2.err: NumericArray  n_data × n_pars × n_pars (second derivatives of err sigma-part)
#' @export
res_cpp <- function(data, out, err = NULL) {
    .Call(`_dMod_res_cpp`, data, out, err)
}

