# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute residuals (Rcpp implementation, optimized)
NULL

res_cpp <- function(data, out, err = NULL) {
    .Call(`_dMod_res_cpp`, data, out, err)
}

